### ISSUE TITLE
MethodBinderWithArgument のInvoke()で、引数を定義型のサブクラスにすると呼び出しに失敗する

### ISSUE THREAD

**Issue by veigr** [ugaya40/Livet#10]
### 概要

`TestMethod(Super arg)` なメソッドを、`Super` のサブクラスの型 `Sub` を引数に呼び出すと `ArgumentException` が発生します。

### 再現手順

以下のコードを実行。

<pre lang="csharp">
using System;
using Livet.Behaviors;

namespace ConsoleApplication1
{
	class Program
	{
		static void Main(string[] args)
		{
			TestNormal();
			TestBinder();
		}

		private static void TestNormal()
		{
			// MethodBinderWithArgument を使わない通常の呼び出し
			Super calleeArg = null;
			var test = new Test(x => calleeArg = x);
			var callerArg = new Sub();
			test.TestMethod(callerArg);
			Console.WriteLine(callerArg == calleeArg);	// True
		}

		private static void TestBinder()
		{
			// MethodBinderWithArgument を使った呼び出し
			Super calleeArg = null;
			var test = new Test(x => calleeArg = x);
			var binder = new MethodBinderWithArgument();
			var callerArg = new Sub();
			binder.Invoke(test, "TestMethod", callerArg);    // ArgumentException となる
			Console.WriteLine(callerArg == calleeArg);
		}
	}

	class Test
	{
		private readonly Action<Super> action;

		public Test(Action<Super> action)
		{
			this.action = action;
		}

		public void TestMethod(Super arg) => this.action?.Invoke(arg);
	}
	class Super { }
	class Sub : Super { }
}
</pre>

### 期待結果

`TestBinder()` の実行結果は `TestNormal()` と同じとなる。

### 実際の結果

`binder.Invoke()` にて `ArgumentException` が発生する。

### 原因

以下の部分で引数のキャスト可否判定に使用している `IsAssignableFrom` の左右が逆と考えられます。

https://github.com/ugaya40/Livet/blob/master/.NET4.0/Livet(.NET4.0)/Behaviors/MethodBinderWithArgument.cs#L76

**Comment by ugaya40** [comment]
https://github.com/ugaya40/Livet/commit/ccc0934e3a2a996a800a9978cf2da8a29f099aac でおそらく治ったと思いますが、Nugetなどバージョンを上げていないので手動でアセンブリ置換などをお願いできましょうでしょうか？

**Comment by veigr** [comment]
ありがとうございます(サンプルコード動かしたやつコピペしたつもりだったんですが何故か動かないやつで申し訳ないです)。

確認しましたところ、 ccc0934 の修正ではメソッドに定義された引数の型が interface の場合に対応できないようです。

```csharp
if ((!parameters[0].ParameterType.IsAssignableFrom(_argumentType))) return false;
```

であれば大丈夫そうであることは確認しましたが、いかがでしょうか？

**Comment by ugaya40** [comment]
今度こそこれで治ったかと・・ https://github.com/ugaya40/Livet/commit/ad6b43fafff5606b5231c536a4816881269ea66d

```
if (parameters[0].ParameterType.IsInterface)
{
    if (!newArgumentType.GetInterfaces().Contains(parameters[0].ParameterType)) return false;
}
else
{
    if ((!_argumentType.IsSubclassOf(parameters[0].ParameterType)) && (_argumentType != parameters[0].ParameterType)) return false;
}
```
にて今まで起きてた問題全部解決したかと思います。

また、いただいたコードの修正版

```
class Program
{
	static void Main(string[] args)
	{
		TestNormal();
		TestBinder();
	}

	private static void TestNormal()
	{
		// MethodBinderWithArgument を使わない通常の呼び出し
		Super calleeArg = null;
		var test = new Test(x => calleeArg = x);
		var callerArg = new Sub();
		test.TestMethod(callerArg);
		Console.WriteLine(callerArg == calleeArg);  // True
		test.TestMethod2(new Other());
	}

	private static void TestBinder()
	{
		// MethodBinderWithArgument を使った呼び出し
		Super calleeArg = null;
		var test = new Test(x => calleeArg = x);
		var binder = new MethodBinderWithArgument();
		var callerArg = new Sub();
		binder.Invoke(test, "TestMethod", callerArg);    // ArgumentException となる
		Console.WriteLine(callerArg == calleeArg);
		binder.Invoke(test,"TestMethod2",new Other());
	}
}

interface TestInterface
{

}

class Test
{
	private readonly Action<Super> action;

	public Test(Action<Super> action)
	{
		this.action = action;
	}

	public void TestMethod(Super arg) => this.action?.Invoke(arg);
	public void TestMethod2(TestInterface t) => this.action?.Invoke(null);
}
class Super { }
class Sub : Super { }
class Other : TestInterface { }
```
にて動作確認いたしました＞＜

**Comment by veigr** [comment]
確認しました。
これで問題ないように思います。
修正ありがとうございました。

**Comment by ugaya40** [comment]
ありがとうございました！
