### ISSUE TITLE
WindowActionMessageのバグ

### ISSUE THREAD

**Issue by EH500Kintarou** [ugaya40/Livet#20]
WindowActionMessageのCreateInstanceCoreメソッドのオーバーライドにバグがあります。
`return new WindowActionMessage(MessageKey);`
となっていますが、正しくは
`return new WindowActionMessage(Action, MessageKey);`
のはずです。
こうしないと、ViewModelからWindowActionMessageをRaiseしたときに、渡したActionがウィンドウに正しく作用しません。

**Comment by runceel** [comment]
この問題って実際に起きてますか？

```
こうしないと、ViewModelからWindowActionMessageをRaiseしたときに、渡したActionがウィンドウに正しく作用しません。
```

こんな基本的な問題が起きてたら過去に issue が上がってそうにも思えるのですが。
個人的には `CreateInstanceCore` の実装は `new WindowActionMessage();` だけでもいいのではと思ったのですが

**Comment by runceel** [comment]
長期間応答がないのでいったんクローズします。
もし、この件で問題が起きてることが明らかなら再オープンしてコメントを追記してください。
（すいません、検証コード書いて問題が再現するかというのに時間が割けなくて…）
