### ISSUE TITLE
nugetの「プロジェクトURL」をGithubに

### ISSUE THREAD

**Issue by terasato** [ugaya40/Livet#23]
nugetの「プロジェクトURL」には，現在 http://ugaya40.hateblo.jp/entry/Livet が指定されていますが，ブログは2014年以来更新されておらず，「仮死状態の」プロジェクトに見えてしまいます。

GithubのプロジェクトページのURLに変更する方が良いのではないでしょうか。

**Comment by runceel** [comment]
ありがとうございます。
まとまったドキュメント的なものがそこにしかないので残していました。

確かに仮死状態に見えるので GitHub に変更したうえで、このページへのリンクを GitHub 上に置く感じにしようと思います。

**Comment by runceel** [comment]
最新版で対応しました。
ありがとうございます。
