### ISSUE TITLE
nugetで2.1.0をインストールするときのエラー

### ISSUE THREAD

**Issue by terasato** [ugaya40/Livet#24]
重大度レベル	コード	説明	プロジェクト	ファイル	行	抑制状態
エラー		参照を追加できませんでした。パッケージ 'LivetCask' はフレームワーク参照を 'Microsoft.Expression.Interactions' に追加しようとしましたが、GAC に見つかりませんでした。これは、パッケージのバグである可能性があります。パッケージの所有者にお問い合わせください。
参照を使用できません。

**Comment by terasato** [comment]
というエラーが表示されるようになってしまいました。私のやり方が間違っているのかもしれませんが… そうであればご教授お願いします。

**Comment by terasato** [comment]
使ったことはありませんでしたが，「Blend for Visual Stuidio 2017」がインストールされています。

**Comment by terasato** [comment]
取り急ぎ，1.3.1を無事インストールできました。進展があれば2.x系に更新したいと思います。

**Comment by runceel** [comment]
Blend本体ではなくBlend for Bisual Studio SDK for .NET を個別のコンポーネントあたりで追加してますか？（すいません、英語版にしててスクショが日本語じゃないです）
![image](https://user-images.githubusercontent.com/79868/50332181-b25f0f00-0544-11e9-86b0-a61e2296cbee.png)

**Comment by terasato** [comment]
お返事遅くなりました。
使っていませんが，SDKだけでなく「Blend for Visual Studio 2017」がインストールされています。
2.2.0でもこの問題は再現しました。

**Comment by runceel** [comment]
ご迷惑をおかけして申し訳ありません。状況を整理させてください。

- Visual Studio 2017 でデスクトップ開発と個別のコンポーネントとして Blend for Visual Studio SDK for .NET にチェックを入れてインストールしている
- .NET Framework 4.5.2 以上をターゲットにして WPF アプリケーションのプロジェクトを作成する
- NuGet から LivetCask 2.2.0 を追加する

上記の状態で

```
重大度レベル	コード	説明	プロジェクト	ファイル	行	抑制状態
エラー	参照を追加できませんでした。パッケージ 'LivetCask' はフレームワーク参照を 'Microsoft.Expression.Interactions' に追加しようとしましたが、GAC に見つかりませんでした。これは、パッケージのバグである可能性があります。パッケージの所有者にお問い合わせください。
参照を使用できません。
```

が出てしまうということであってますか？

一つ確認していただきたい内容として WPF アプリのプロジェクトを作成して参照の追加から `Assemblies -> Framework` の中（すいません英語設定でVS使ってるので日本語だと表記がカタカナかもしれません）に `Microsoft.Expression.Interactions` と `System.Windows.Interactivity` はありますか？
私の Visual Studio だとこのように Version 4.5.0.0 があります。

![image](https://user-images.githubusercontent.com/79868/52195715-67068300-289c-11e9-8032-82c5bdbaa50e.png)

**Comment by terasato** [comment]
お返事ありがとうございます。

「Visual Studio 2017 でデスクトップ開発と個別のコンポーネントとして `Blend for Visual Studio SDK for .NET` にチェックを入れてインストールしている」ではなく，「`Blend for Visual Studio for VS2017`をインストール」していました。

ご指摘の通り，参照の画面でアセンブリを検索してみたところ，2つのアセンブリが見当たりませんでしたので，Visual Studio Installerで`Blend for Visual Studio SDK for .NET`を選択してインストールしたところ問題は解決しました。

しょうもないことでお時間をお取りしてしまい済みませんでした。

**Comment by runceel** [comment]
無事使えるようになったようでよかったです。
なかなかわかりにくいところにあるので厄介ですよね。

また何かあったらお気軽にご質問ください。
