### ISSUE TITLE
DispatcherCollection.Dispatcherはnull許容ですか？

### ISSUE THREAD

**Issue by terasato** [ugaya40/Livet#31]
経緯：
 - LivetにはReSharperの[External Annotations](https://www.jetbrains.com/help/resharper/Code_Analysis__External_Annotations.html)用のファイルが用意されていないことに気づきました。自分で作ってしまおうと考え，現在作成中です
 - `null`許容かどうかを調査してみたところ，`null`チェックが抜けている部分を複数発見しましたので， terasato:AddParamChecks としてプルリクを出しました（まだまだ出てくると思います

調査で気づいたのですが，`DispatcherCollection.Dispatcher`は
   - setterで`null`チェックがありません（`null`が代入されうる状態）
   - ライブラリ内で`null`チェックなくメソッド呼び出しがされています（`NullReferenceException`がスローされる可能性があります。例：`Dispatcher.CheckAccess()`）

`DispatcherCollection.Dispatcher`は`null`許容として設計されているのであれば，メソッド呼び出しに`null`チェックを追加する必要があります。`null`非許容として設計されているのであれば（そう思ってライブラリを使っていました），setterに`null`チェックを追加する必要があります。

類似の問題はまだまだ出てきそうな感じがしています。安定性向上のため，お付き合いよろしくお願いします。

**Comment by runceel** [comment]
ありがとうございます～プルリク受け入れました。
